spring:
  application:
    name: db-service
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8300
  ssl:
    enabled: false


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost